name: Download Docker Image
on: [workflow_dispatch]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: docker pull nginx:latest
      - name: Save Image as Tar
        run: docker save nginx:latest -o nginx.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nginx-image
          path: nginx.tar
